version: "3.8"

x-app: &app
  build: .
  volumes:
    - .:/app/:cached
    - bundle:/usr/local/bundle/
  depends_on:
    - postgres
    - redis
  env_file:
    - .development.env

services:
  postgres:
    image: postgres:14
    volumes:
      - postgres:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - fcloud
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:alpine
    networks:
      - fcloud
    volumes:
      - redis:/data/

  app:
    <<: *app
    tty: true
    ports:
      - "3000:3000"
    networks:
      - fcloud
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.koira-tls.redirectscheme.scheme: "https"

      traefik.http.routers.koira.rule: "Host(`koira.cloud.dejonckhee.re`)"
      traefik.http.routers.koira.entrypoints: "web"
      traefik.http.routers.koira.middlewares: "koira-tls"

      traefik.http.routers.koira-tls.rule: "Host(`koira.cloud.dejonckhee.re`)"
      traefik.http.routers.koira-tls.entrypoints: "websecure"
      traefik.http.routers.koira-tls.tls: "true"
      traefik.http.routers.koira-tls.tls.certresolver: "letsencrypt"

      traefik.http.services.koira.loadbalancer.server.port: "3000"

  sidekiq:
    <<: *app
    networks:
      - fcloud
    command: bundle exec sidekiq

volumes:
  postgres:
  redis:
  bundle:

networks:
  fcloud:
    name: fcloud_default
